default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: course_management_development

test:
  <<: *default
  database: course_management_test

production:
  <<: *default
  database: course_management_production
